import React, { useState } from "react";
import { PlusCircle, Upload, MapPin, Tag, CheckCircle2, Clock, Image as ImageIcon, ThumbsUp, Navigation, AlertCircle, User, ArrowRight } from "lucide-react";
import { CATEGORY_LABELS } from "../utils/departmentAssigner";

/**
 * CitizenView Component
 * 
 * Props:
 * - complaints: Array of complaint objects from App.jsx state
 * - onAddComplaint: Function passed from App.jsx to append new complaint to state
 * - onUpvote: Function passed from App.jsx to increment upvote count
 */
export default function CitizenView({ complaints, onAddComplaint, onUpvote, userName, setUserName }) {
  // Input state for the login form field
  const [loginInput, setLoginInput] = useState("");

  // Local state variables for form input fields
  const [category, setCategory] = useState("pothole");
  const [description, setDescription] = useState("");
  const [location, setLocation] = useState("");
  
  // Geolocation states for GPS position capture
  const [coords, setCoords] = useState(null);
  const [geoStatus, setGeoStatus] = useState("idle"); // 'idle' | 'loading' | 'captured' | 'denied'
  const [geoMessage, setGeoMessage] = useState("");

  // Local state for selected photo file and preview URL generated by URL.createObjectURL
  const [photoFile, setPhotoFile] = useState(null);
  const [photoPreview, setPhotoPreview] = useState(null);

  // Success message toast state
  const [successMessage, setSuccessMessage] = useState("");

  if (!userName) {
    return (
      <div className="max-w-md mx-auto px-4 py-16">
        <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-200 text-center space-y-6">
          <div className="w-14 h-14 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center mx-auto border border-blue-100">
            <User className="w-7 h-7" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-slate-900">Citizen Portal Sign-In</h2>
            <p className="text-xs text-slate-500 mt-1">
              Enter your name to access neighborhood reporting and community tracking.
            </p>
          </div>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (loginInput.trim()) {
                setUserName(loginInput.trim());
              }
            }}
            className="space-y-4 text-left"
          >
            <div>
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1.5">
                Full Name
              </label>
              <input
                type="text"
                required
                value={loginInput}
                onChange={(e) => setLoginInput(e.target.value)}
                placeholder="e.g. Rahul Sharma"
                className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition"
              />
            </div>
            <button
              type="submit"
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl shadow-md shadow-blue-600/20 transition text-sm flex items-center justify-center gap-2 cursor-pointer"
            >
              <span>Continue to Citizen Portal</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </form>
        </div>
      </div>
    );
  }

  const handleGetLocation = () => {
    if (!navigator.geolocation) {
      setGeoStatus("denied");
      setGeoMessage("Location access denied — browser does not support geolocation.");
      return;
    }

    setGeoStatus("loading");

    navigator.geolocation.getCurrentPosition(
      (position) => {
        const { latitude, longitude } = position.coords;
        setCoords({ lat: latitude, lng: longitude });
        setGeoStatus("captured");
        setGeoMessage(`📍 Location captured (${latitude.toFixed(4)}, ${longitude.toFixed(4)})`);
      },
      (error) => {
        console.warn("Geolocation permission or position error:", error.message);
        setGeoStatus("denied");
        setGeoMessage("Location access denied — you can still submit with just the address");
      },
      { enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 }
    );
  };

  const handlePhotoChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setPhotoFile(file);
      const objectUrl = URL.createObjectURL(file);
      setPhotoPreview(objectUrl);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!description.trim() || !location.trim()) {
      alert("Please provide both location and description for the issue.");
      return;
    }

    const newComplaint = {
      category: category,
      description: description.trim(),
      location: location.trim(),
      photoUrl: photoPreview || null,
      lat: coords ? coords.lat : null,
      lng: coords ? coords.lng : null,
    };

    onAddComplaint(newComplaint);

    setSuccessMessage("Complaint submitted successfully! It has been routed to the respective department.");
    setTimeout(() => setSuccessMessage(""), 5000);

    setDescription("");
    setLocation("");
    setPhotoFile(null);
    setPhotoPreview(null);
    setCategory("pothole");
    setCoords(null);
    setGeoStatus("idle");
    setGeoMessage("");
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case "Pending":
        return (
          <span className="inline-flex items-center gap-1 bg-amber-100 text-amber-800 text-xs font-semibold px-2.5 py-1 rounded-full border border-amber-200">
            <Clock className="w-3.5 h-3.5" /> Pending
          </span>
        );
      case "In Progress":
        return (
          <span className="inline-flex items-center gap-1 bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-1 rounded-full border border-blue-200">
            <Clock className="w-3.5 h-3.5 animate-spin text-blue-600" /> In Progress
          </span>
        );
      case "Resolved":
        return (
          <span className="inline-flex items-center gap-1 bg-emerald-100 text-emerald-800 text-xs font-semibold px-2.5 py-1 rounded-full border border-emerald-200">
            <CheckCircle2 className="w-3.5 h-3.5" /> Resolved
          </span>
        );
      default:
        return null;
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      
      {/* View Header */}
      <div className="mb-8 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Citizen Portal</h2>
          <p className="text-sm text-slate-600">
            Report civic issues in your neighborhood. Submissions are automatically routed to the responsible city department.
          </p>
        </div>

        <div className="flex items-center gap-3 bg-white px-4 py-2 rounded-2xl border border-slate-200 shadow-sm self-start sm:self-auto">
          <span className="text-xs text-slate-600">
            Welcome, <strong className="text-slate-900 font-semibold">{userName}</strong>
          </span>
          <button
            onClick={() => {
              setUserName("");
              setLoginInput("");
            }}
            className="text-[11px] font-semibold text-blue-700 bg-blue-50 hover:bg-blue-100 border border-blue-200 px-2.5 py-1 rounded-lg transition cursor-pointer"
          >
            Switch User
          </button>
        </div>
      </div>

      {/* Success Notification Alert */}
      {successMessage && (
        <div className="mb-6 bg-emerald-50 border border-emerald-200 text-emerald-800 px-4 py-3 rounded-xl flex items-center gap-2 shadow-sm animate-fade-in">
          <CheckCircle2 className="w-5 h-5 text-emerald-600 flex-shrink-0" />
          <span className="text-sm font-medium">{successMessage}</span>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* LEFT COLUMN: Issue Submission Form */}
        <div className="lg:col-span-5">
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 sticky top-24">
            <div className="flex items-center space-x-2 pb-4 mb-5 border-b border-slate-100">
              <PlusCircle className="w-5 h-5 text-blue-600" />
              <h3 className="text-lg font-semibold text-slate-900">Report a New Issue</h3>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4">
              
              {/* Category Dropdown */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                  Category (Auto-assigns Department)
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                >
                  <option value="pothole">Pothole / Road Repair (→ Public Works)</option>
                  <option value="garbage">Garbage Overflow (→ Sanitation)</option>
                  <option value="streetlight">Streetlight Fault (→ Electrical)</option>
                  <option value="water">Water Leakage (→ Water Supply)</option>
                </select>
              </div>

              {/* Location Input */}
              <div>
                <div className="flex items-center justify-between mb-1 flex-wrap gap-1">
                  <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider">
                    Location / Address
                  </label>
                  
                  {/* Share My Location Button */}
                  <button
                    type="button"
                    onClick={handleGetLocation}
                    disabled={geoStatus === "loading"}
                    className="inline-flex items-center gap-1 text-[11px] font-semibold text-blue-700 bg-blue-50 hover:bg-blue-100 border border-blue-200 px-2.5 py-1 rounded-lg transition disabled:opacity-50 cursor-pointer"
                  >
                    <Navigation className={`w-3 h-3 text-blue-600 ${geoStatus === "loading" ? "animate-spin" : ""}`} />
                    <span>{geoStatus === "loading" ? "Locating..." : "📍 Use My Current Location"}</span>
                  </button>
                </div>

                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <MapPin className="h-4 w-4 text-slate-400" />
                  </div>
                  <input
                    type="text"
                    required
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    placeholder="e.g. 142 Main Street, near City Park"
                    className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl pl-9 pr-3 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                  />
                </div>

                {/* Geolocation Feedback Indicators */}
                {geoStatus === "captured" && (
                  <p className="text-xs text-emerald-600 font-semibold flex items-center gap-1 mt-1.5 bg-emerald-50 p-2 rounded-lg border border-emerald-200">
                    <CheckCircle2 className="w-3.5 h-3.5 flex-shrink-0" />
                    <span>📍 Location captured</span>
                  </p>
                )}

                {geoStatus === "denied" && (
                  <p className="text-xs text-amber-800 bg-amber-50 p-2.5 rounded-lg border border-amber-200 flex items-center gap-1.5 mt-1.5">
                    <AlertCircle className="w-4 h-4 text-amber-600 flex-shrink-0" />
                    <span>Location access denied — you can still submit with just the address</span>
                  </p>
                )}
              </div>

              {/* Description Input */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                  Issue Description
                </label>
                <textarea
                  rows="3"
                  required
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Describe the issue in detail..."
                  className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all resize-none"
                />
              </div>

              {/* Photo Upload Input */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                  Upload Photo (Optional Preview)
                </label>
                
                <div className="flex items-center gap-3">
                  <label className="cursor-pointer bg-slate-100 hover:bg-slate-200 border border-slate-300 text-slate-700 text-xs font-medium px-4 py-2.5 rounded-xl transition flex items-center gap-2">
                    <Upload className="w-4 h-4 text-slate-500" />
                    <span>Select Photo</span>
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handlePhotoChange}
                      className="hidden"
                    />
                  </label>
                  
                  {photoFile && (
                    <span className="text-xs text-slate-500 truncate max-w-[150px]">
                      {photoFile.name}
                    </span>
                  )}
                </div>

                {photoPreview && (
                  <div className="mt-3 relative rounded-xl overflow-hidden border border-slate-200 shadow-sm max-h-40 bg-slate-100">
                    <img
                      src={photoPreview}
                      alt="Local Photo Preview"
                      className="w-full h-36 object-cover"
                    />
                  </div>
                )}
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 rounded-xl shadow-md shadow-blue-600/20 hover:shadow-lg transition-all flex items-center justify-center space-x-2 text-sm mt-2"
              >
                <PlusCircle className="w-4 h-4" />
                <span>Submit Complaint</span>
              </button>

            </form>
          </div>
        </div>

        {/* RIGHT COLUMN: Citizen's Track Complaints List with UPVOTE BUTTON */}
        <div className="lg:col-span-7 space-y-4">
          <div className="flex items-center justify-between pb-2 border-b border-slate-200">
            <h3 className="text-lg font-semibold text-slate-900">
              Track & Upvote Community Complaints ({complaints.length})
            </h3>
            <span className="text-xs text-slate-500">Upvotes increase issue priority score</span>
          </div>

          {complaints.length === 0 ? (
            <div className="bg-white p-8 rounded-2xl border border-slate-200 text-center text-slate-500">
              <ImageIcon className="w-10 h-10 mx-auto text-slate-300 mb-2" />
              <p>No complaints reported yet. Submit your first issue using the form!</p>
            </div>
          ) : (
            <div className="space-y-4">
              {complaints.map((item) => (
                <div
                  key={item.id}
                  className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-all flex flex-col sm:flex-row gap-4"
                >
                  {/* Photo Thumbnail */}
                  {item.photoUrl ? (
                    <div className="w-full sm:w-28 h-28 rounded-xl overflow-hidden bg-slate-100 flex-shrink-0 border border-slate-200">
                      <img
                        src={item.photoUrl}
                        alt="Issue photo"
                        className="w-full h-full object-cover"
                        onError={(e) => {
                          e.target.src = "https://images.unsplash.com/photo-1590059306054-94a28f7ff282?auto=format&fit=crop&w=300&q=80";
                        }}
                      />
                    </div>
                  ) : (
                    <div className="w-full sm:w-28 h-28 rounded-xl bg-slate-100 flex flex-col items-center justify-center text-slate-400 flex-shrink-0 border border-slate-200">
                      <ImageIcon className="w-6 h-6 mb-1" />
                      <span className="text-[10px]">No Photo</span>
                    </div>
                  )}

                  {/* Complaint Details */}
                  <div className="flex-1 space-y-2">
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <span className="text-xs font-mono font-medium text-slate-400">{item.id}</span>
                        <h4 className="text-base font-semibold text-slate-900 capitalize">
                          {CATEGORY_LABELS[item.category] || item.category}
                        </h4>
                      </div>
                      <div>{getStatusBadge(item.status)}</div>
                    </div>

                    <p className="text-sm text-slate-700 leading-relaxed line-clamp-2">
                      {item.description}
                    </p>

                    <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-slate-100">
                      <div className="flex items-center gap-3 text-xs text-slate-500">
                        <span className="flex items-center gap-1">
                          <MapPin className="w-3.5 h-3.5 text-slate-400" />
                          {item.location}
                        </span>
                        <span className="flex items-center gap-1 font-medium text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md">
                          <Tag className="w-3.5 h-3.5" />
                          {item.department}
                        </span>
                      </div>

                      {/* FEATURE 1: UPVOTE BUTTON & COUNTER */}
                      <button
                        onClick={() => onUpvote(item.id)}
                        className="flex items-center gap-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 text-xs font-semibold px-3 py-1.5 rounded-lg border border-blue-200 transition active:scale-95 shadow-sm"
                        title="Click to upvote this issue"
                      >
                        <ThumbsUp className="w-3.5 h-3.5 text-blue-600" />
                        <span>Upvote ({item.upvotes || 0})</span>
                      </button>
                    </div>

                  </div>
                </div>
              ))}
            </div>
          )}

        </div>

      </div>
    </div>
  );
}
